# Essential site settings.
title: Site template
language: en-US # Language for the site.
email: changeme@example.org
description: > # Ignore newlines until "baseurl:"
  Basic site template.
baseurl: "" # Subpath of the site, if applicable.
url: "https://example.org" # Base protocol and hostname.
github_url: https://github.com/example
twitter_url: https://twitter.com/example
instagram_url: https://instagram.com/example
facebook_url: https://facebook.com/example
linkedin_url: https://www.linkedin.com/in/example

# Essential build settings.
markdown: kramdown # Default.
highlighter: rouge # Default.
permalink: /:categories/:year/:month/:day/:title

# Default to creating a sitemap for better crawling.
plugins:
  - jekyll-sitemap